---
name: "Bug report"
description: "Report a bug with the integration"
labels: "Bug"
body:
- type: markdown
  attributes:
    value: |
      ## Before opening an issue
      
      **STOP!** Most "bugs" are actually setup or vehicle state issues. Please verify ALL of the following before submitting:
      
      1. **Wake up your vehicle** - Press the "Request Wake Up" button in Home Assistant. Vehicles in sleep mode won't report EV data.
      2. **Check the official app** - Verify the data appears in the Kia Connect / Hyundai BlueLink / Genesis app first.
      3. **Restart Home Assistant** - Many issues resolve after a restart.
      4. **Check your subscription** - Kia Connect / BlueLink requires an active subscription for remote features.
      
      Search through [existing issues](https://github.com/MarcusTaz/ha_kia_hyundai_USA/issues?q=is%3Aissue) to see if others have had the same problem.

- type: checkboxes
  attributes:
    label: Pre-submission checklist
    description: "You MUST complete ALL of these steps before submitting"
    options:
      - label: I have pressed the "Request Wake Up" button and waited 2-3 minutes for data to refresh
        required: true
      - label: I have verified the data I expect appears in the official Kia/Hyundai/Genesis app
        required: true
      - label: I have restarted Home Assistant after initial setup
        required: true
      - label: My Kia Connect / BlueLink / Genesis Connected Services subscription is active
        required: true
      - label: This issue is NOT about missing sensors immediately after setup (vehicles need to be woken up first)
        required: true

- type: input
  attributes:
    label: "Vehicle Year and Model"
    description: "e.g., 2024 EV6, 2023 Ioniq 5, 2025 GV60"
    placeholder: "2024 EV6"
  validations:
    required: true

- type: dropdown
  attributes:
    label: "Brand"
    options:
      - Kia
      - Hyundai
      - Genesis
  validations:
    required: true

- type: dropdown
  attributes:
    label: "Is this a new setup or did it previously work?"
    options:
      - New setup - never worked
      - Was working before, stopped working
      - Worked in original/archived integration, not working in this one
  validations:
    required: true

- type: textarea
  attributes:
    label: "System Health details"
    description: "Paste the data from the System Health card in Home Assistant"
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Debug logging
    options:
      - label: I have enabled debug logging for my installation.
        required: true
      - label: I have filled out the issue template to the best of my ability.
        required: true
      - label: This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
        required: true
      - label: This issue is not a duplicate of an [existing issue](https://github.com/MarcusTaz/ha_kia_hyundai_USA/issues?q=is%3Aissue).
        required: true

- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to fix. Issues without reproduction steps may be closed."
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true

- type: textarea
  attributes:
    label: "Debug logs"
    description: "Enable debug logs (https://www.home-assistant.io/integrations/logger/) and include everything from startup to the issue."
    render: text
  validations:
    required: true

- type: textarea
  attributes:
    label: "Diagnostics dump"
    description: "Drag the diagnostics dump file here. (Settings > Devices & Services > Integration > 3-dot menu > Download diagnostics)"
